CREATE TABLE [User].[UserDetail]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserId] BIGINT NOT NULL,
	[FirstName] NVARCHAR(128) NOT NULL,
	[MiddleName] NVARCHAR(128),
	[LastName] NVARCHAR(128) NOT NULL,
	[DateOfBirth] DATETIME NOT NULL,
	[PrimaryContact] NVARCHAR(128) NOT NULL,
	[SecondaryContact] NVARCHAR(128),
	[AlternateEmail] NVARCHAR(128),
	[AddressLine1] NVARCHAR(255) NOT NULL,
	[AddressLine2] NVARCHAR(255),
	[AddressArea] NVARCHAR(64),
	[AddressCity] NVARCHAR(64) NOT NULL,
	[AddressState] NVARCHAR(64) NOT NULL,
	[AddressPostCode] NVARCHAR(12) NOT NULL,
	[AddressCountry] NVARCHAR(64) NOT NULL,
	[PostalLine1] NVARCHAR(255),
	[PostalLine2] NVARCHAR(255),
	[PostalArea] NVARCHAR(64),
	[PostalCity] NVARCHAR(64),
	[PostalState] NVARCHAR(64),
	[PostalPostCode] NVARCHAR(12),
	[PostalCountry] NVARCHAR(64), 
    [UseAddressAsPostal] BIT NOT NULL,
)